### ISSUE TITLE
Collector and Route Server ASN

### ISSUE THREAD

**Issue by andydavidson** [euro-ix/json-schemas#24]
Although the IXP collector and route-server data appears as a member in the member_list, it would be helpful to specifically list the exchange point operator's own collector and route-server in the ixp_list section.  

I have extended my own ixp_list schema for internal use with 'asn_collector' and 'asn_routeserver' fields.

**Comment by barryo** [comment]
@andydavidson - this has been implemented in v0.7 but with a bit more flexibility due to the way some IXs use the same ASNs for many different things.

See description in #25 and also more info in commit 6fe3bb04fbc9ba78e529bbce97cff3a23031d89c
