### ISSUE TITLE
Method to register L1-only POPs

### ISSUE THREAD

**Issue by durkovic** [euro-ix/json-schemas#27]
ixp_list { } currently supports info about different IX POPs described by colo/city/country/pdb_facility_id via the switch { } array.

It would make sense to introduce a similar method to describe L1-only POPs, i.e. the ones not having any switch.

**Comment by nickhilliard** [comment]
yep, this is one of the things that we deliberately didn't model in the schema because it adds extra parsing complication.  The easiest option would be to use a switch entry.
