### ISSUE TITLE
Tag Releases on GitHub

### ISSUE THREAD

**Issue by timwattenberg** [euro-ix/json-schemas#32]
Please use the _[Releases](https://github.com/euro-ix/json-schemas/releases)_-Feature of GitHub to tag the releases.

This would be helpful to let GitHub notify you on new releases and also I just added this to our teams Slack-Channel via the (hidden) RSS-feed:
`/feed subscribe https://github.com/euro-ix/json-schemas/releases.atom`

Thanks :)

**Comment by nickhilliard** [comment]
good idea.  we'll do this for future releases.

**Comment by timwattenberg** [comment]
Please create a GH-Release for v1.0 😉 (cc @nickhilliard)

**Comment by barryo** [comment]
[Done](https://github.com/euro-ix/json-schemas/releases/tag/v1.0) 😄

**Comment by timwattenberg** [comment]
Thanks! This is great... Just FYI:

E-Mail Notification:
<img width="1271" alt="Bildschirmfoto 2019-07-23 um 09 19 54" src="https://user-images.githubusercontent.com/120251/61715541-57d0a000-ad2b-11e9-8605-a06232caabdc.png">
GitHub Notification:
<img width="744" alt="Bildschirmfoto 2019-07-23 um 09 20 40" src="https://user-images.githubusercontent.com/120251/61715542-58693680-ad2b-11e9-8af3-2d109bfa6476.png">
Slack Notification:
<img width="650" alt="Bildschirmfoto 2019-07-23 um 09 21 04" src="https://user-images.githubusercontent.com/120251/61715544-58693680-ad2b-11e9-87b3-210381e8d95b.png">

No excuse _we didn't know about this_ anymore 😉👍
