### ISSUE TITLE
Trying to JSON parse ixp-member-list-1.0.schema.json raises a SyntaxError

### ISSUE THREAD

**Issue by vegu** [euro-ix/json-schemas#35]
Trying against https://raw.githubusercontent.com/euro-ix/json-schemas/master/versions/ixp-member-list-1.0.schema.json

```
$.get(
  'https://raw.githubusercontent.com/euro-ix/json-schemas/master/versions/ixp-member-list-1.0.schema.json', 
  function(response) { console.log(JSON.parse(response))  }
)

VM180:404 Uncaught SyntaxError: Unexpected token } in JSON at position 15850
```

Edit: Other versions (0.7, 0.6 etc.) work as expected

**Comment by nickhilliard** [comment]
that's the schema, not the json data.  The schema has been tested and validates correctly against json schema draft 4.

**Comment by vegu** [comment]
The schema itself is still a json formatted file that should be parseable by a json parser, no? It works for all the older version of the schema

**Comment by nickhilliard** [comment]
right, maybe there is an issue here after all: trailing commas are not legitimate in json. Some validators accept this and others don't.

**Comment by nickhilliard** [comment]
Can you take a look at this version:

https://raw.githubusercontent.com/euro-ix/json-schemas/master/ixp-member-list.schema.json

**Comment by vegu** [comment]
@nickhilliard that one worked

**Comment by nickhilliard** [comment]
great, i've retro-pushed this into v1.0.  thanks for the pointer!
