### ISSUE TITLE
Apply ISO 3166 to switch location as well as IXP location

### ISSUE THREAD

**Issue by leovegoda** [euro-ix/json-schemas#39]
v1.0 of the schema requires that the location of the IXP should be specified using a code from ISO 3166. In contrast, the switch location is defined without reference to ISO 3166. This means users can use a country name, which is not unambiguous and makes automation and analysis more challenging. Tightening the specification to require ISO 3166 codes would be good. When doing this, it would be helpful to specify use of the Alpha-2 code so that implementers do not need to also build in support for Alpha-3 and Numeric codes.

**Comment by nickhilliard** [comment]
good catch - i've updated the wiki docs to this effect.

**Comment by jiri-janousek** [comment]
Hello @nickhilliard. Is there any plan to update the JSON schemas in the repository as well?

**Comment by nickhilliard** [comment]
i've updated this in v1.1 (https://github.com/euro-ix/json-schemas/commit/00e5a569c32fa18bdc7f514ba01342df49e567e5)
