### ISSUE TITLE
GitHub project "About" links to a 404

### ISSUE THREAD

**Issue by bluikko** [euro-ix/json-schemas#41]
The project main page contains on the top-right an "About" box with content and a broken link:
```console
JSON Schema for Exporting IXP Participant Details

ixpdb.euro-ix.net/en/ixpdb/providers/
```

The [link](https://ixpdb.euro-ix.net/en/ixpdb/providers/) is broken with a 404 and should perhaps be updated.  
It results in an error page that complaints about a missing 404 error page.

**Comment by nickhilliard** [comment]
@bijals can you fix the ^^^ URL?

**Comment by bijals** [comment]
@bluikko @nickhilliard it's fixed, thanks for pointing it out!

**Comment by nickhilliard** [comment]
super thx!
